### PR TITLE
refactor(fusionauth): update e2e-tests with version 1.50.1

### PR DESCRIPTION
**Pull request by Aaron-Ritter**
- add latest version 1.50.1
- remove version tag from docker-compose.yml files
- remove fusionauth versions older than 6 months
- remove fusionauth patch versions older than latest for each minor version
- add FusionAuth latest weekly test to automatically test the latest tag available

### CODE REVIEW

**Comment by Aaron-Ritter** [comment]
New FusionAuth version 1.50.1 causes:

```
io.fusionauth.sdk.FullEnd2EndTest > e2eTest[emulator-5554 - 10] FAILED 
	kotlinx.serialization.MissingFieldException: Field 'email_verified' is required for type with serial name 'io.fusionauth.mobilesdk.UserInfo', but it was missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:95)
```

**Review by Aaron-Ritter — COMMENTED** [review]
todo: add email and profile scope configuration to 1.50.1 kickstart

**Comment by Aaron-Ritter** [comment]
Unknown scope policy - Reject.

image

Does not show / cause an error and is just stuck on a blank page:
image

image

**Comment by Aaron-Ritter** [comment]
https://github.com/FusionAuth/fusionauth-android-sdk/issues/64

**Review by ColinFrick — APPROVED** [review]
LGTM

**Pull request merged**
